about:
  name: wTemplateTreeResolver
  description: >-
    Class to resolve tree-like data structures with links  or paths in the
    structure. Use the module to resolve template or path to value.
  version: 0.5.0
  enabled: 0
  interpreters:
    - njs >= 10.0.0
    - chrome >= 60.0.0
    - firefox >= 60.0.0
  keywords:
    - Template tree
    - wTools
  license: MIT
  author: Kostiantyn Wandalen <wanalen@01.school>
  contributors:
    - Kostiantyn Wandalen <wanalen@01.school>
  npm.name: wtemplatetreeresolver
  npm.scripts:
    test: 'wtest .run proto/** v:5'
path:
  repository: 'git+https:///github.com/Wandalen/wTemplateTreeResolver.git'
  origins:
    - 'git+https:///github.com/Wandalen/wTemplateTreeResolver.git'
    - 'npm:///wtemplatetreeresolver'
  bugtracker: 'https:///github.com/Wandalen/wTemplateTreeResolver/issues'
step:
  proto.export:
    inherit: module.export
    export: 'path::export'
    tar: 0
    criterion:
      content: proto
  doc.export:
    inherit: module.export
    export: 'path::doc'
    tar: 0
    criterion:
      content: doc
  npm.export:
    inherit: module.export
    export: out.npm
    tar: 0
    criterion:
      content: npm
  npm.publish:
    shell: npm publish
build:
  proto.export:
    criterion:
      content: proto
      export: 1
    steps:
      - 'step::proto.export'
  doc.export:
    criterion:
      content: doc
      export: 1
    steps:
      - 'step::doc.export'
  npm.export:
    criterion:
      content: npm
      export: 1
    steps:
      - 'step::npm.publish'
  export:
    criterion:
      default: 1
      export: 1
    steps:
      - 'build::proto.export'
